/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
//import Beans.Denuncia;
import Beans.Doacao;
//import DAO.DenunciaDAO;
import DAO.DoacaoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author diegu
 */
public class TelaDoacaoUs extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaDoacaoUs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDoar = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        txtTipoPagamento = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDoar.setContentAreaFilled(false);
        btnDoar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDoar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 190, 100));

        txtUsername.setBackground(new java.awt.Color(131, 181, 229));
        txtUsername.setBorder(null);
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 520, 20));

        txtTipoPagamento.setBackground(new java.awt.Color(131, 181, 229));
        txtTipoPagamento.setBorder(null);
        getContentPane().add(txtTipoPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 520, 20));

        txtValor.setBackground(new java.awt.Color(131, 181, 229));
        txtValor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor.setBorder(null);
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 150, 50));

        txtSenha.setBackground(new java.awt.Color(131, 181, 229));
        txtSenha.setBorder(null);
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 310, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Tela de Doação Water.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        btnVoltar.setContentAreaFilled(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 160, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoarActionPerformed

        String username = txtUsername.getText();
        double valor = Double.parseDouble(txtValor.getText());
        String pagamento = txtTipoPagamento.getText();
        String senha = txtSenha.getText();
        
        if(username.isEmpty() || senha.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.");
        return;
    }

    // Criar uma instância do LoginDAO
    DAO.LoginDAO loginDAO = new DAO.LoginDAO();
    DAO.AgentesDAO agentesDAO = new DAO.AgentesDAO();

    // Tentar autenticar o usuário
    Beans.Login usuários = loginDAO.autenticar(username, senha);
    Beans.Agentes agentes = agentesDAO.autenticar(username, senha);

    // Verificar se o login foi bem-sucedido
    if (usuários != null) {
        
        Doacao c = new Doacao();
        c.setUsername(username);
        c.setPagamento(pagamento);
        c.setValor(valor);
        c.setSenha(senha);
        
        JOptionPane.showMessageDialog(this, "Doacao bem-sucedida! Obrigado pela sua colaboracao!" );
        
        DoacaoDAO doacaoDAO = new DoacaoDAO();
        doacaoDAO.cadastrarDoacao(c);
        
        txtUsername.setText("");
        txtTipoPagamento.setText("");
        txtValor.setText("");
        txtSenha.setText("");
        
        //Abre a proxima tela principal
        TelaPrincipalUs principal = new TelaPrincipalUs();
        this.dispose();  // Fecha a tela de login
        principal.setVisible(true);  // Abre a próxima tela

    } else if(agentes != null){
        
        Doacao c = new Doacao();
        c.setUsername(username);
        c.setPagamento(pagamento);
        c.setValor(valor);
        c.setSenha(senha);
        
        JOptionPane.showMessageDialog(this, "Doacao bem-sucedida! Obrigado pela sua colaboracao!" );
        
        DoacaoDAO doacaoDAO = new DoacaoDAO();
        doacaoDAO.cadastrarDoacao(c);
        
        txtUsername.setText("");
        txtTipoPagamento.setText("");
        txtValor.setText("");
        txtSenha.setText("");
        
        //Abre a proxima tela principal
        TelaPrincipalUs principal = new TelaPrincipalUs();
        this.dispose();  // Fecha a tela de login
        principal.setVisible(true);  // Abre a próxima tela
        
    } else {
        // Falha no login
        JOptionPane.showMessageDialog(this, "Username ou senha incorretos. Tente novamente.");
    }
    }//GEN-LAST:event_btnDoarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaPrincipalUs principal = new TelaPrincipalUs();
        this.dispose();  // Fecha a tela de login
        principal.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDoacaoUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDoacaoUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDoacaoUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDoacaoUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDoacaoUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtTipoPagamento;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

}
