/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author diegu
 */
public class TelaPrincipalAg extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipalAg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDeslogar = new javax.swing.JButton();
        btnDoacao = new javax.swing.JButton();
        btnDenuncia = new javax.swing.JButton();
        btnInstituicao = new javax.swing.JButton();
        btnAcessarDenuncia = new javax.swing.JButton();
        btnAvaliacao = new javax.swing.JButton();
        btnCriadores = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDeslogar.setContentAreaFilled(false);
        btnDeslogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeslogarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeslogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 160, 30));

        btnDoacao.setContentAreaFilled(false);
        btnDoacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoacaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 190, 200));

        btnDenuncia.setContentAreaFilled(false);
        btnDenuncia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDenuncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDenunciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDenuncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 200, 200));

        btnInstituicao.setContentAreaFilled(false);
        btnInstituicao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstituicaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnInstituicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, 190, 200));

        btnAcessarDenuncia.setContentAreaFilled(false);
        btnAcessarDenuncia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcessarDenuncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessarDenunciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcessarDenuncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 190, 200));

        btnAvaliacao.setContentAreaFilled(false);
        btnAvaliacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliacaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvaliacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 190, 200));

        btnCriadores.setContentAreaFilled(false);
        btnCriadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCriadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriadoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnCriadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 190, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Tela principalAg Water.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeslogarActionPerformed
        TelaLogin telaLogin = new TelaLogin();
        this.dispose();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_btnDeslogarActionPerformed

    private void btnDenunciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDenunciaActionPerformed
        TelaDenunciaAg telaDenuncia = new TelaDenunciaAg();
        this.dispose();
        telaDenuncia.setVisible(true);
    }//GEN-LAST:event_btnDenunciaActionPerformed

    private void btnDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoacaoActionPerformed
        TelaDoacaoAg telaDoacao = new TelaDoacaoAg();
        this.dispose();
        telaDoacao.setVisible(true);
    }//GEN-LAST:event_btnDoacaoActionPerformed

    private void btnInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstituicaoActionPerformed
        TelaInstituicaoAg telaInstituicao = new TelaInstituicaoAg();
        this.dispose();
        telaInstituicao.setVisible(true);
    }//GEN-LAST:event_btnInstituicaoActionPerformed

    private void btnCriadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriadoresActionPerformed
        TelaCriadoresAg telaCriadores = new TelaCriadoresAg();
        this.dispose();
        telaCriadores.setVisible(true);
    }//GEN-LAST:event_btnCriadoresActionPerformed

    private void btnAcessarDenunciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarDenunciaActionPerformed
        TelaAcessarDenuncias telaAcDenuncia = new TelaAcessarDenuncias();
        this.dispose();
        telaAcDenuncia.setVisible(true);
    }//GEN-LAST:event_btnAcessarDenunciaActionPerformed

    private void btnAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliacaoActionPerformed
        TelaAvaliaçãoAg telaAva = new TelaAvaliaçãoAg();
        this.dispose();
        telaAva.setVisible(true);
    }//GEN-LAST:event_btnAvaliacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalAg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessarDenuncia;
    private javax.swing.JButton btnAvaliacao;
    private javax.swing.JButton btnCriadores;
    private javax.swing.JButton btnDenuncia;
    private javax.swing.JButton btnDeslogar;
    private javax.swing.JButton btnDoacao;
    private javax.swing.JButton btnInstituicao;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
