/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import Beans.Denuncia;
import DAO.DenunciaDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author diegu
 */
public class TelaDenunciaAg extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaDenunciaAg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDenunciar = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtLocal = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDenunciar.setContentAreaFilled(false);
        btnDenunciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDenunciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDenunciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 190, 100));

        txtUsername.setBackground(new java.awt.Color(131, 181, 229));
        txtUsername.setBorder(null);
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 520, 20));

        txtDescricao.setBackground(new java.awt.Color(131, 181, 229));
        txtDescricao.setBorder(null);
        getContentPane().add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 520, 80));

        txtLocal.setBackground(new java.awt.Color(131, 181, 229));
        txtLocal.setBorder(null);
        getContentPane().add(txtLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 520, 20));

        txtCep.setBackground(new java.awt.Color(131, 181, 229));
        txtCep.setBorder(null);
        getContentPane().add(txtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 310, 20));

        txtSenha.setBackground(new java.awt.Color(131, 181, 229));
        txtSenha.setBorder(null);
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 310, 20));

        btnVoltar.setContentAreaFilled(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Tela de Denuncia Water.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDenunciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDenunciarActionPerformed

        String username = txtUsername.getText();
        String descricao = txtDescricao.getText();
        int cep = Integer.parseInt(txtCep.getText());
        String local = txtLocal.getText();
        String senha = txtSenha.getText();
        
        if(username.isEmpty() || senha.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.");
        return;
    }

    // Criar uma instância do LoginDAO
    DAO.LoginDAO loginDAO = new DAO.LoginDAO();
    DAO.AgentesDAO agentesDAO = new DAO.AgentesDAO();

    // Tentar autenticar o usuário
    Beans.Login usuários = loginDAO.autenticar(username, senha);
    Beans.Agentes agentes = agentesDAO.autenticar(username, senha);

    // Verificar se o login foi bem-sucedido
    if (usuários != null) {
        
        Denuncia c = new Denuncia();
        c.setUsername(username);
        c.setDescricao(descricao);
        c.setCep(cep);
        c.setLocal(local);
        c.setSenha(senha);
        
        JOptionPane.showMessageDialog(this, "Denuncia bem-sucedida!" );
        
        DenunciaDAO denunciaDAO = new DenunciaDAO();
        denunciaDAO.cadastrarDenuncia(c);
        
        txtUsername.setText("");
        txtDescricao.setText("");
        txtCep.setText("");
        txtLocal.setText("");
        txtSenha.setText("");
        
        //Abre a proxima tela principal
        TelaPrincipalAg principal = new TelaPrincipalAg();
        this.dispose();  // Fecha a tela de login
        principal.setVisible(true);  // Abre a próxima tela
        
    } else if(agentes != null){
        
        Denuncia c = new Denuncia();
        c.setUsername(username);
        c.setDescricao(descricao);
        c.setCep(cep);
        c.setLocal(local);
        c.setSenha(senha);
        
        JOptionPane.showMessageDialog(this, "Denuncia bem-sucedida!" );
        
        DenunciaDAO denunciaDAO = new DenunciaDAO();
        denunciaDAO.cadastrarDenuncia(c);
        
        txtUsername.setText("");
        txtDescricao.setText("");
        txtCep.setText("");
        txtLocal.setText("");
        txtSenha.setText("");
        
        //Abre a proxima tela principal
        TelaPrincipalAg principal = new TelaPrincipalAg();
        this.dispose();  // Fecha a tela de login
        principal.setVisible(true);  // Abre a próxima tela

    } else {
        // Falha no login
        JOptionPane.showMessageDialog(this, "Username ou senha incorretos. Tente novamente.");
    }
    }//GEN-LAST:event_btnDenunciarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaPrincipalAg principal = new TelaPrincipalAg();
        this.dispose();  // Fecha a tela de login
        principal.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDenunciaAg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDenunciaAg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDenunciaAg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDenunciaAg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDenunciaAg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDenunciar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
