/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Beans.Cadastro;
import DAO.CadastroDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diegu
 */
public class TelaLogin extends javax.swing.JFrame {

    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastroAg = new javax.swing.JButton();
        btnCadastroUs = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastroAg.setContentAreaFilled(false);
        btnCadastroAg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastroAg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroAgActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastroAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 340, 130, 30));

        btnCadastroUs.setContentAreaFilled(false);
        btnCadastroUs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastroUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroUsActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastroUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 130, 30));

        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 530, 90));

        txtSenha.setBackground(new java.awt.Color(25, 95, 161));
        txtSenha.setBorder(null);
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 430, 20));

        txtUsername.setBackground(new java.awt.Color(25, 95, 161));
        txtUsername.setBorder(null);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 430, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Tela de Login Water.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    String username = txtUsername.getText();
    String senha = String.valueOf(txtSenha.getPassword());

    // Verificar se os campos não estão vazios
    if(username.isEmpty() || senha.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.");
        return;
    }

    // Criar uma instância do LoginDAO
    DAO.LoginDAO loginDAO = new DAO.LoginDAO();
    DAO.AgentesDAO agentesDAO = new DAO.AgentesDAO();

    // Tentar autenticar o usuário
    Beans.Login usuários = loginDAO.autenticar(username, senha);
    Beans.Agentes agentes = agentesDAO.autenticar(username, senha);

    // Verificar se o login foi bem-sucedido
    if (usuários != null) {
        // Sucesso no login
        JOptionPane.showMessageDialog(this, "Login bem-sucedido! Bem-vindo, " + usuários.getUsername());

        //Abre a proxima tela principal
        TelaPrincipalUs principal = new TelaPrincipalUs();
        this.dispose();  // Fecha a tela de login
        principal.setVisible(true);  // Abre a próxima tela

        
    // Verificar se o login foi bem-sucedido
    }   if(agentes != null){
        // Sucesso no login
        JOptionPane.showMessageDialog(this, "Login bem-sucedido! Bem-vindo, " + agentes.getUsername());

        //Abre a proxima tela principal
       TelaPrincipalAg principal = new TelaPrincipalAg();
       this.dispose();  // Fecha a tela de login
       principal.setVisible(true);  // Abre a próxima tela
        
        
    } else {
        // Falha no login
        JOptionPane.showMessageDialog(this, "Username ou senha incorretos. Tente novamente.");
        
    }
    
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnCadastroUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroUsActionPerformed
        TelaCadastroUs telacadastrous = new TelaCadastroUs();
        this.dispose();
        telacadastrous.setVisible(true);
    }//GEN-LAST:event_btnCadastroUsActionPerformed

    private void btnCadastroAgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroAgActionPerformed
        TelaCadastroAg telacadastroag = new TelaCadastroAg();
        this.dispose();
        telacadastroag.setVisible(true);
    }//GEN-LAST:event_btnCadastroAgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroAg;
    private javax.swing.JButton btnCadastroUs;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
