/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import Beans.Avaliacao;
import DAO.AvaliacaoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author diegu
 */
public class TelaAvaliaçãoUs extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaAvaliaçãoUs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAvaliar = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        txtCritica = new javax.swing.JTextField();
        txtNota = new javax.swing.JTextField();
        txtMelhorar = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAvaliar.setContentAreaFilled(false);
        btnAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvaliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 190, 100));

        txtUsername.setBackground(new java.awt.Color(131, 181, 229));
        txtUsername.setBorder(null);
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 520, 20));

        txtCritica.setBackground(new java.awt.Color(131, 181, 229));
        txtCritica.setBorder(null);
        getContentPane().add(txtCritica, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 520, 20));

        txtNota.setBackground(new java.awt.Color(131, 181, 229));
        txtNota.setBorder(null);
        getContentPane().add(txtNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 520, 20));

        txtMelhorar.setBackground(new java.awt.Color(131, 181, 229));
        txtMelhorar.setBorder(null);
        getContentPane().add(txtMelhorar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 310, 20));

        txtSenha.setBackground(new java.awt.Color(131, 181, 229));
        txtSenha.setBorder(null);
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 310, 20));

        btnVoltar.setContentAreaFilled(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Tela de Avaliação Water.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliarActionPerformed

        String username = txtUsername.getText();
        String critica = txtCritica.getText();
        int nota = Integer.parseInt(txtNota.getText());
        String melhorar = txtMelhorar.getText();
        String senha = txtSenha.getText();
        
        if(username.isEmpty() || senha.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.");
        return;
    }

    // Criar uma instância do LoginDAO
    DAO.LoginDAO loginDAO = new DAO.LoginDAO();
    DAO.AgentesDAO agentesDAO = new DAO.AgentesDAO();

    // Tentar autenticar o usuário
    Beans.Login usuários = loginDAO.autenticar(username, senha);
    Beans.Agentes agentes = agentesDAO.autenticar(username, senha);

    // Verificar se o login foi bem-sucedido
    if (usuários != null) {
        
        Avaliacao a = new Avaliacao();
        a.setUsername(username);
        a.setCritica(critica);
        a.setNota(nota);
        a.setMelhorar(melhorar);
        a.setSenha(senha);
        
        JOptionPane.showMessageDialog(this, "Avaliacao bem-sucedida!" );
        
        AvaliacaoDAO avaliacaoDAO = new AvaliacaoDAO();
        avaliacaoDAO.cadastrarAvaliacao(a);
        
        txtUsername.setText("");
        txtCritica.setText("");
        txtMelhorar.setText("");
        txtNota.setText("");
        txtSenha.setText("");
        
        //Abre a proxima tela principal
        TelaPrincipalUs principal = new TelaPrincipalUs();
        this.dispose();  // Fecha a tela de login
        principal.setVisible(true);  // Abre a próxima tela

    } else if(agentes != null){
        
        Avaliacao a = new Avaliacao();
        a.setUsername(username);
        a.setCritica(critica);
        a.setNota(nota);
        a.setMelhorar(melhorar);
        a.setSenha(senha);
        
        JOptionPane.showMessageDialog(this, "Avaliacao bem-sucedida!" );
        
        AvaliacaoDAO avaliacaoDAO = new AvaliacaoDAO();
        avaliacaoDAO.cadastrarAvaliacao(a);
        
        txtUsername.setText("");
        txtCritica.setText("");
        txtMelhorar.setText("");
        txtNota.setText("");
        txtSenha.setText("");
        
        //Abre a proxima tela principal
        TelaPrincipalUs principal = new TelaPrincipalUs();
        this.dispose();  // Fecha a tela de login
        principal.setVisible(true);  // Abre a próxima tela
        
    } else {
        // Falha no login
        JOptionPane.showMessageDialog(this, "Username ou senha incorretos. Tente novamente.");
    }
    }//GEN-LAST:event_btnAvaliarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaPrincipalUs principal = new TelaPrincipalUs();
        this.dispose();  // Fecha a tela de login
        principal.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAvaliaçãoUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAvaliaçãoUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAvaliaçãoUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAvaliaçãoUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAvaliaçãoUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtCritica;
    private javax.swing.JTextField txtMelhorar;
    private javax.swing.JTextField txtNota;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
